# rime/plum 預設配方

extend = "rime.toml"

[tasks.Rx-prelude]
description = "℞ 默認配置"
extend = "recipe"
env = {RECIPE = "prelude"}

[tasks.Rx-luna-pinyin]
description = "℞ 朙月拼音"
extend = "recipe"
env = {RECIPE = "luna-pinyin"}

[tasks.Rx-terra-pinyin]
description = "℞ 地球拼音"
extend = "recipe"
env = {RECIPE = "terra-pinyin"}

[tasks.Rx-cangjie]
description = "℞ 倉頡五代"
extend = "recipe"
env = {RECIPE = "cangjie"}
